##
# Main query object
#

type Query {

  ##
  # Fetches a user by name
  #

  user (name: String!): User

  ##
  # Fetches users by age or gender
  #

  users (age: Number, gender: Gender): [User]

  ##
  # Fetches a pet by name or owner name
  #

  pet (name: String, owner: String): Pet

  ##
  # Fetches pets by age or gender
  #

  pets (age: Number, gender: Gender): [Pet]
}
