##
# Animal types
#

enum AnimalType {
  Dog,
  Cat
}

##
# Animal interface implemented
# by the Pet type
#

interface Animal {
  gender: Gender!
  name: String!
  type: AnimalType!
  age: Number!
}
